name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # or any version you need

      - name: Install dependencies
        run: |
          npm install
          npm install -g truffle  # or any other framework you're using

      - name: Run Tests
        run: truffle test  # or npx hardhat test

      - name: Analyze Security
        run: |
          npm install -g slither
          slither .  # or any other security tool command
