name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '22.0.0'  # Specify your desired Node.js version

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Deploy to local network
      run: |
        # Start your local blockchain node (if necessary)
        # You may need to adjust the command based on your setup
        ganache-cli -p 22001 -h 0.0.0.0 &

        # Wait for the blockchain node to be ready
        sleep 10  # Adjust time as needed

        # Deploy your contract
        npx truffle migrate --network development
